/* AUTO-GENERATED — do not edit. Run: python backend/scripts/generate_demo_profiles.py */
export const DEMO_PROFILES = [
  {
    "id": "user-1431216",
    "name": "Клиент 15k",
    "sourceUserId": 1431216,
    "targetMonthlyIncomeRub": 15000,
    "targetIncomeEurYear": 1800.0,
    "modelIncomeEurYear": 3731.79,
    "displayIncomeRubMonth": 31098.25,
    "incomeQuantile": 0.0,
    "age": 20,
    "balance": 3731.79,
    "balanceSource": "income_lag_90_proxy",
    "sex": 0,
    "sexLabel": "Женщина",
    "seniorityMonths": 9,
    "isNewCustomer": 0,
    "segment": "STUDENTS",
    "regionName": "CIUDAD REAL",
    "ownedProducts": [
      "card-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Студент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 15 000 ₽/мес.",
    "characteristics": [
      "Стартовый доход",
      "Профиль из реального датасета"
    ]
  },
  {
    "id": "user-1452428",
    "name": "Клиент 100k",
    "sourceUserId": 1452428,
    "targetMonthlyIncomeRub": 100000,
    "targetIncomeEurYear": 12000.0,
    "modelIncomeEurYear": 12024.39,
    "displayIncomeRubMonth": 100203.25,
    "incomeQuantile": 0.0002,
    "age": 21,
    "balance": 12024.39,
    "balanceSource": "income_lag_90_proxy",
    "sex": 0,
    "sexLabel": "Женщина",
    "seniorityMonths": 8,
    "isNewCustomer": 0,
    "segment": "STUDENTS",
    "regionName": "SEVILLA",
    "ownedProducts": [
      "card-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Студент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 100 000 ₽/мес.",
    "characteristics": [
      "Стартовый доход",
      "Профиль из реального датасета"
    ]
  },
  {
    "id": "user-449839",
    "name": "Клиент 500k",
    "sourceUserId": 449839,
    "targetMonthlyIncomeRub": 500000,
    "targetIncomeEurYear": 60000.0,
    "modelIncomeEurYear": 60000.12,
    "displayIncomeRubMonth": 500001.0,
    "incomeQuantile": 0.1168,
    "age": 59,
    "balance": 60000.12,
    "balanceSource": "income_lag_90_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 149,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "HUESCA",
    "ownedProducts": [
      "card-2",
      "srv-3"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 1,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 500 000 ₽/мес.",
    "characteristics": [
      "Высокий доход",
      "Профиль из реального датасета"
    ]
  },
  {
    "id": "user-916185",
    "name": "Клиент 5000k",
    "sourceUserId": 916185,
    "targetMonthlyIncomeRub": 5000000,
    "targetIncomeEurYear": 600000.0,
    "modelIncomeEurYear": 599962.14,
    "displayIncomeRubMonth": 4999684.5,
    "incomeQuantile": 0.9939,
    "age": 38,
    "balance": 599962.14,
    "balanceSource": "income_lag_90_proxy",
    "sex": 0,
    "sexLabel": "Женщина",
    "seniorityMonths": 59,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "MADRID",
    "ownedProducts": [
      "card-2",
      "rko-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 1,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета  выбранный рядом с уровнем дохода 5 000 000 ₽/мес.",
    "characteristics": [
      "Высокий доход",
      "Есть бизнес-продукты",
      "Профиль из реального датасета"
    ]
  }
] as const
