/* AUTO-GENERATED — do not edit. Run: python backend/scripts/generate_demo_profiles.py */
export const DEMO_PROFILES = [
  {
    "id": "user-1311548",
    "name": "Матвей",
    "sourceUserId": 1311548,
    "targetIncomeQuantile": 0.01,
    "targetIncomeEurYear": 30359.55,
    "modelIncomeEurYear": 30359.55,
    "incomeQuantile": 0.01,
    "age": 35,
    "balance": 10625.84,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 26,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "VALLADOLID",
    "ownedProducts": [
      "card-2"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета, выбранный рядом с p01 дохода.",
    "characteristics": [
      "Стабильный доход",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 30359.55
  },
  {
    "id": "user-1249522",
    "name": "Артем",
    "sourceUserId": 1249522,
    "targetIncomeQuantile": 0.2,
    "targetIncomeEurYear": 70065.69,
    "modelIncomeEurYear": 70065.69,
    "incomeQuantile": 0.2,
    "age": 38,
    "balance": 24522.99,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 26,
    "isNewCustomer": 0,
    "segment": "VIP",
    "regionName": "ASTURIAS",
    "ownedProducts": [
      "rko-1"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 0,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 1,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Премиум",
    "description": "Реальный клиент из датасета, выбранный рядом с p20 дохода.",
    "characteristics": [
      "Стабильный доход",
      "Есть бизнес-продукты",
      "Профиль из реального датасета"
    ],
    "scoringIncome": 70065.69
  },
  {
    "id": "user-910614",
    "name": "Даниил",
    "sourceUserId": 910614,
    "targetIncomeQuantile": 0.7,
    "targetIncomeEurYear": 131739.18,
    "modelIncomeEurYear": 131739.18,
    "incomeQuantile": 0.7,
    "age": 37,
    "balance": 46108.71,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 61,
    "isNewCustomer": 0,
    "segment": "INDIVIDUALS",
    "regionName": "VALLADOLID",
    "ownedProducts": [
      "card-1",
      "rko-2",
      "loan-4",
      "card-3"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 0,
      "dep-5": 0,
      "card-1": 1,
      "card-5": 0,
      "rko-2": 1,
      "rko-3": 0,
      "rko-4": 0,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 0,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 0,
      "loan-5": 0,
      "biz-4": 0,
      "dep-6": 0,
      "loan-4": 1,
      "card-3": 1
    },
    "info": "Частный клиент",
    "description": "Реальный клиент из датасета, выбранный рядом с p70 дохода.",
    "characteristics": [
      "Стабильный доход",
      "Есть кредитные продукты",
      "Есть бизнес-продукты"
    ],
    "scoringIncome": 131739.18
  },
  {
    "id": "user-187420",
    "name": "Михаил",
    "sourceUserId": 187420,
    "targetIncomeQuantile": 0.99,
    "targetIncomeEurYear": 498721.5,
    "modelIncomeEurYear": 498724.11,
    "incomeQuantile": 0.99,
    "age": 42,
    "balance": 174553.44,
    "balanceSource": "income_share_proxy",
    "sex": 1,
    "sexLabel": "Мужчина",
    "seniorityMonths": 189,
    "isNewCustomer": 0,
    "segment": "VIP",
    "regionName": "MADRID",
    "ownedProducts": [
      "card-2",
      "rko-4",
      "rko-1",
      "srv-3",
      "loan-5",
      "biz-4"
    ],
    "ownedProductFlags": {
      "dep-7": 0,
      "card-2": 1,
      "dep-5": 0,
      "card-1": 0,
      "card-5": 0,
      "rko-2": 0,
      "rko-3": 0,
      "rko-4": 1,
      "dep-9": 0,
      "dep-1": 0,
      "dep-3": 0,
      "rko-1": 1,
      "dep-2": 0,
      "loan-2": 0,
      "card-4": 0,
      "loan-1": 0,
      "srv-3": 1,
      "loan-5": 1,
      "biz-4": 1,
      "dep-6": 0,
      "loan-4": 0,
      "card-3": 0
    },
    "info": "Премиум",
    "description": "Реальный клиент из датасета, выбранный рядом с p99 дохода.",
    "characteristics": [
      "Стабильный доход",
      "Есть кредитные продукты",
      "Есть бизнес-продукты"
    ],
    "scoringIncome": 498724.11
  }
] as const
